/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CityCard`; params?: Router.UnknownInputParams; } | { pathname: `/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/AppointmentReciept`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/CreateAppointmentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/SelectDoctor`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ScanQRScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SuccessScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/PatientScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/registration/PatientRegistration`; params?: Router.UnknownInputParams; } | { pathname: `/registration/PatientUpdate`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/auth/signup/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CityCard`; params?: Router.UnknownOutputParams; } | { pathname: `/hospitals`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/AppointmentReciept`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/CreateAppointmentScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/SelectDoctor`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/ScanQRScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SuccessScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/PatientScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/registration/PatientRegistration`; params?: Router.UnknownOutputParams; } | { pathname: `/registration/PatientUpdate`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/auth/signup/[projectId]`, params: Router.UnknownOutputParams & { projectId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/CityCard${`?${string}` | `#${string}` | ''}` | `/hospitals${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/appointments/AppointmentReciept${`?${string}` | `#${string}` | ''}` | `/appointments/CreateAppointmentScreen${`?${string}` | `#${string}` | ''}` | `/appointments/SelectDoctor${`?${string}` | `#${string}` | ''}` | `/auth/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/auth/LoginScreen${`?${string}` | `#${string}` | ''}` | `/auth/ScanQRScreen${`?${string}` | `#${string}` | ''}` | `/auth/SignupScreen${`?${string}` | `#${string}` | ''}` | `/auth/SuccessScreen${`?${string}` | `#${string}` | ''}` | `/dashboard/DashboardScreen${`?${string}` | `#${string}` | ''}` | `/dashboard/PatientScreen${`?${string}` | `#${string}` | ''}` | `/dashboard/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/registration/PatientRegistration${`?${string}` | `#${string}` | ''}` | `/registration/PatientUpdate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CityCard`; params?: Router.UnknownInputParams; } | { pathname: `/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/AppointmentReciept`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/CreateAppointmentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/SelectDoctor`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ScanQRScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SuccessScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/PatientScreen`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/registration/PatientRegistration`; params?: Router.UnknownInputParams; } | { pathname: `/registration/PatientUpdate`; params?: Router.UnknownInputParams; } | `/+not-found` | `/auth/signup/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/auth/signup/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } };
    }
  }
}
